blank_issues_enabled: false
contact_links:
  - name: Ask a question or get help
    url: https://github.com/lehungquangminh/WinNest/discussions
    about: Please ask questions and get support here instead of creating issues.
